In [ ]:
download("https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data", "house.data")

In [1]:
# read csv file
data = readdlm("house.data", Float64)

506×14 Array{Float64,2}:
 0.00632  18.0   2.31  0.0  0.538  6.575  …  296.0  15.3  396.9    4.98  24.0
 0.02731   0.0   7.07  0.0  0.469  6.421     242.0  17.8  396.9    9.14  21.6
 0.02729   0.0   7.07  0.0  0.469  7.185     242.0  17.8  392.83   4.03  34.7
 0.03237   0.0   2.18  0.0  0.458  6.998     222.0  18.7  394.63   2.94  33.4
 0.06905   0.0   2.18  0.0  0.458  7.147     222.0  18.7  396.9    5.33  36.2
 0.02985   0.0   2.18  0.0  0.458  6.43   …  222.0  18.7  394.12   5.21  28.7
 0.08829  12.5   7.87  0.0  0.524  6.012     311.0  15.2  395.6   12.43  22.9
 0.14455  12.5   7.87  0.0  0.524  6.172     311.0  15.2  396.9   19.15  27.1
 0.21124  12.5   7.87  0.0  0.524  5.631     311.0  15.2  386.63  29.93  16.5
 0.17004  12.5   7.87  0.0  0.524  6.004     311.0  15.2  386.71  17.1   18.9
 0.22489  12.5   7.87  0.0  0.524  6.377  …  311.0  15.2  392.52  20.45  15.0
 0.11747  12.5   7.87  0.0  0.524  6.009     311.0  15.2  396.9   13.27  18.9
 0.09378  12.5   7.87  0.0  0.524  5.88

In [2]:
# 14th column is label others are features, so extract them
y = data[:, 14]
x = data[:, 1:13]
x = x.'

13×506 Array{Float64,2}:
   0.00632    0.02731    0.02729  …    0.06076    0.10959    0.04741
  18.0        0.0        0.0           0.0        0.0        0.0    
   2.31       7.07       7.07         11.93      11.93      11.93   
   0.0        0.0        0.0           0.0        0.0        0.0    
   0.538      0.469      0.469         0.573      0.573      0.573  
   6.575      6.421      7.185    …    6.976      6.794      6.03   
  65.2       78.9       61.1          91.0       89.3       80.8    
   4.09       4.9671     4.9671        2.1675     2.3889     2.505  
   1.0        2.0        2.0           1.0        1.0        1.0    
 296.0      242.0      242.0         273.0      273.0      273.0    
  15.3       17.8       17.8      …   21.0       21.0       21.0    
 396.9      396.9      392.83        396.9      393.45     396.9    
   4.98       9.14       4.03          5.64       6.48       7.88   

In [3]:
y = reshape(y, 1, 506)

1×506 Array{Float64,2}:
 24.0  21.6  34.7  33.4  36.2  28.7  …  16.8  22.4  20.6  23.9  22.0  11.9

In [4]:
sample_mean = mean(x, 2)
sample_std = std(x, 2)
# normalize
x = (x .- sample_mean) ./ sample_std

13×506 Array{Float64,2}:
 -0.419367  -0.416927  -0.416929  …  -0.413038  -0.407361  -0.41459 
  0.284548  -0.48724   -0.48724      -0.48724   -0.48724   -0.48724 
 -1.28664   -0.592794  -0.592794      0.115624   0.115624   0.115624
 -0.272329  -0.272329  -0.272329     -0.272329  -0.272329  -0.272329
 -0.144075  -0.73953   -0.73953       0.157968   0.157968   0.157968
  0.413263   0.194082   1.28145   …   0.983986   0.724955  -0.362408
 -0.119895   0.366803  -0.265549      0.796661   0.736268   0.434302
  0.140075   0.556609   0.556609     -0.772919  -0.667776  -0.61264 
 -0.981871  -0.867024  -0.867024     -0.981871  -0.981871  -0.981871
 -0.665949  -0.986353  -0.986353     -0.802418  -0.802418  -0.802418
 -1.45756   -0.302794  -0.302794  …   1.1753     1.1753     1.1753  
  0.440616   0.440616   0.396035      0.440616   0.402826   0.440616
 -1.0745    -0.491953  -1.20753      -0.982076  -0.864446  -0.668397

In [5]:
# split dataset
training_set_size = 400
rng = srand(1)
r = randperm(rng, size(x, 2))
training_x = x[:, r[1:training_set_size]]
training_y = y[r[1:training_set_size]]
test_x = x[:, r[training_set_size+1:end]]
test_y = y[r[training_set_size+1:end]];



In [39]:
srand(1)
weights = randn((1, 13)) * 0.1
# check std to see if true
# In report it does not seem to have 0.1 std despite the objective. 
# It also might not has seed of 1.
print(std(weights))

0.10507935760753251

In [40]:
function predict(weights, trn_data)
    return weights * trn_data
end

predict (generic function with 1 method)

In [41]:
ypred = predict(weights, training_x)

1×400 Array{Float64,2}:
 0.255258  -0.243474  -0.586728  -0.265922  …  -0.947298  0.475033  0.222322

In [46]:
function MSELoss(weights, trn_data, labels)
    y_preds = predict(weights, trn_data)
    loss = sum((y_preds .- labels).^2) / (2length(labels))
    return loss
end

MSELoss (generic function with 1 method)

In [47]:
println(MSELoss(weights, training_x, training_y'))
println(MSELoss(weights, test_x, test_y'))
# crazy loss...

296.4410518432671
300.5843998677503


In [ ]:
# TODO update weight with gradient descent